### ISSUE TITLE
Setting for box's default width from toolbar (60%)

### ISSUE THREAD

**Issue by chtiland** [selfthinker/dokuwiki_plugin_wrap#228] opened 2021-04-06 15:29 UTC
It would be nice to be able to set the default size for boxes from toolbar. I also have to change 60% for 80% as I prefer this size.

**Comment by Klap-in** [comment] 2022-08-09 21:30
Duplicate of #193 and  #233.

**Closed by Klap-in** 2022-08-09 21:30 UTC
