### ISSUE TITLE
When using the wrap plugin inside an included page, section edit button is incorrect

### ISSUE THREAD

**Issue by estechnical** [selfthinker/dokuwiki_plugin_wrap#91] opened 2015-02-02 08:56 UTC
If I use the wrap plugin with the include plugin and place a `<WRAP ...> ... </WRAP>` item inside an included page, the section edit button (shown below the included item when viewing the page) doesn't work correctly.

If I view a page that includes a file (containing a WRAP) the corresponding section edit button incorrectly directs me to editing the whole article, not the included section.

If I remove the `<WRAP ...> </WRAP>` tags from the included document, the section edit button works as expected again.

**Comment by estechnical** [comment] 2015-02-02 09:12
Example to reproduce:
You will require the Wrap and Include plugins, create two pages as per below to reproduce the effect. View page1 to see the issue with the edit button. Edit page2 and remove the WRAP tags, then view page1 again, this time the section edit button will correctly edit the included page (page2), not page1.

page1:
    This is a test page.
    {{page>includes:page2}}

page2 (the included item):
    <WRAP important #precautions 70%>
    Some warning
    </WRAP>

**Comment by estechnical** [comment] 2015-02-02 09:27
Just FYI, I also tried out the Box plugin and the section edit buttons work as expected with my test case (obviously replcaing the WRAP tags with appropriate box tags).

**Comment by selfthinker** [comment] 2015-05-04 12:57
The example you gave in your second comment cannot be used to reproduce this. You missed the section from the include.

Unless I misunderstood you, you mean `{{page>include:page2#heading}}` would open the whole page?
I see two different edit buttons, one of them works as expected and leads to the section in the included page, and the other opens the whole of the included page.

**Comment by selfthinker** [comment] 2016-04-03 13:36
Closing due to missing feedback.

**Closed by selfthinker** 2016-04-03 13:36 UTC
Labels: bug
