### ISSUE TITLE
... in Headers

### ISSUE THREAD

**Issue by Lethert** [selfthinker/dokuwiki_plugin_wrap#93] opened 2015-03-19 19:54 UTC
I think htis will create an false output! I think here is a problem with ... (3 dots) in Headlines

```
<div justify>

==== Dies ist ein test... (is false) ====

Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext Dies ist ein Demotext 

...test (is ok)

===== ..testende (is ok, with 2 dots) =====

===== ...testende (is false) =====
</div>
```

**Comment by selfthinker** [comment] 2015-05-04 12:43
This is a duplicate of #75.
It seems to happen with all text substitutions in headings, e.g. "...", "(c)", "->" and also acronyms (WWW, CSS, etc).

**Closed by selfthinker** 2015-05-04 12:43 UTC
